checkout: git clone --recursive https://github.com/edwardstock/toolbox.git .
commands:
  test:
    steps:
      - run: rm -rf _build
      - run: bash .circleci/test.sh

  build_and_package:
    steps:
      - run: bash cfg/package_make.sh -t package -o "-DTOOLBOX_PACKAGING=On"
      - run: bash _build/package_upload.sh -t bintray

  make_project:
    steps:
      - test
      - build_and_package

jobs:
  centos_el7:
    image: docker.edwardstock.com/gcc_dev_el7:latest
    env:
      BINTRAY_USER: edwardstock
      BINTRAY_API_KEY: $ENV
    steps:
      - yum -y install boost-devel
      - make_project

  centos_el8:
    image: docker.edwardstock.com/gcc_dev_el8:latest
    env:
      BINTRAY_USER: edwardstock
      BINTRAY_API_KEY: $ENV
    steps:
      - make_project

  fedora_fc32:
    image: docker.edwardstock.com/gcc_dev_fc32:latest
    env:
      BINTRAY_USER: edwardstock
      BINTRAY_API_KEY: $ENV
    steps:
      - make_project

  fedora_fc33:
    image: docker.edwardstock.com/gcc_dev_fc33:latest
    env:
      BINTRAY_USER: edwardstock
      BINTRAY_API_KEY: $ENV
    steps:
      - make_project

  fedora_fc34:
    image: docker.edwardstock.com/gcc_dev_fc34:latest
    env:
      BINTRAY_USER: edwardstock
      BINTRAY_API_KEY: $ENV
      CXXFLAGS: "-Wno-maybe-uninitialized"
    steps:
      - make_project

  debian_jessie:
    image: docker.edwardstock.com/gcc_dev_debian_jessie:latest
    env:
      BINTRAY_USER: edwardstock
      BINTRAY_API_KEY: $ENV
    steps:
      - apt-get -y install libboost-regex-dev
      - make_project

  debian_stretch:
    image: docker.edwardstock.com/gcc_dev_debian_stretch:latest
    env:
      BINTRAY_USER: edwardstock
      BINTRAY_API_KEY: $ENV
    steps:
      - make_project

  debian_buster:
    image: docker.edwardstock.com/gcc_dev_debian_buster:latest
    env:
      BINTRAY_USER: edwardstock
      BINTRAY_API_KEY: $ENV
    steps:
      - make_project

  ubuntu_xenial:
    image: docker.edwardstock.com/gcc_dev_ubuntu_xenial:latest
    env:
      BINTRAY_USER: edwardstock
      BINTRAY_API_KEY: $ENV
    steps:
      - apt-get -y install libboost-regex-dev
      - make_project

  ubuntu_bionic:
    image: docker.edwardstock.com/gcc_dev_ubuntu_bionic:latest
    env:
      BINTRAY_USER: edwardstock
      BINTRAY_API_KEY: $ENV
    steps:
      - apt-get -y install libboost-regex-dev
      - make_project

  ubuntu_focal:
    image: docker.edwardstock.com/gcc_dev_ubuntu_focal:latest
    env:
      BINTRAY_USER: edwardstock
      BINTRAY_API_KEY: $ENV
    steps:
      - make_project

  ubuntu_groovy:
    image: docker.edwardstock.com/gcc_dev_ubuntu_groovy:latest
    env:
      BINTRAY_USER: edwardstock
      BINTRAY_API_KEY: $ENV
    steps:
      - make_project

