name: C/C++ CI

on:
  push:
      branches: [ main ]
  pull_request:
      branches: [ main ]

jobs:
  build-and-test:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - name: install cppunit
          run: sudo apt install -y gcc-12 python3 cmake
        - name: install conan
          run: |
            pip3 install conan===2.0.17 --break-system-packages
            conan profile autodetect
        - name: configure
          run: |
            mkdir build
            cd build
            conan install ../conanfile.txt --build=missing -of .
            cmake -S .. -B . -DCMAKE_BUILD_TYPE=Release
        - name: make
          run: cmake --build . --target dydx-client -- -j4
